export const INITIAL_COMPANY_STATE = {
  departments: [
    {
      id: 'nexus',
      name: 'NEXUS',
      phase: 'Phase 9 — Context Bridge',
      status: 'active',
      currentState: 'Phase 8.75 complete. Foundation clean. Execution OS upgrade in progress.',
      nextAction: 'Complete Phase 3 execution engine and premium UI upgrade.',
      blockers: [],
      urgency: 'normal',
      lastUpdated: '2026-03-27T00:00:00.000Z',
      metrics: {},
    },
    {
      id: 'hephaestus',
      name: 'HEPHAESTUS',
      phase: 'V4-P7C — RANGE Intelligence Phase 2 Complete',
      status: 'active',
      currentState: 'VORTEX Phase 2 implemented and verified. 10/10 deterministic tests passing. Full suite 13 files / 30 tests passed.',
      nextAction: 'Resume VORTEX with evidence-first verification sequence, then define Phase 3 RANGE plan.',
      blockers: [],
      urgency: 'normal',
      lastUpdated: '2026-03-25T00:00:00.000Z',
      metrics: {},
    },
    {
      id: 'xenon',
      name: 'XENON',
      phase: 'Phase 4 — Complete',
      status: 'paused',
      currentState: 'Department structure complete. Campaign template and channel tracker ready.',
      nextAction: 'Decide channel (Twitter/X or LinkedIn) and first content format to unblock first campaign.',
      blockers: ['Channel decision pending'],
      urgency: 'low',
      lastUpdated: '2026-03-22T00:00:00.000Z',
      metrics: {},
    },
    {
      id: 'aureon',
      name: 'AUREON',
      phase: 'Phase 1 — Active Execution',
      status: 'active',
      currentState: 'System built and operational. Target: €1,000 within 72 hours. Offer: Abandoned Cart Recovery.',
      nextAction: 'Run lead analysis on 10 Shopify stores and send 10 DMs today.',
      blockers: [],
      urgency: 'critical',
      lastUpdated: '2026-03-26T00:00:00.000Z',
      metrics: { revenueTarget: 1000, revenueCurrency: 'EUR' },
    },
  ],
};
